<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [3]:
x = 10
assert x >= 0, "x is becoming negative!"

In [4]:
x = -1
assert x >= 0, "x is becoming negative!"

AssertionError: x is becoming negative!

### 1.2 try-except

In [5]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.2
The square of 2 is 4!


In [10]:
try:
    number=input("Give me a number and I will calculate its square. ")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square. jhj
Oh oh! I cannot square jhj!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [7]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c

In [8]:
funny_add(1, 2)           # Two positional, 1 default
#> 121
funny_add(1, 2, 3)        # Three positional
#> 321
funny_add(a=1, b=2)       # Two keyword, 1 default
#> 121
funny_add(c=3, b=1, a=2)  # Three keyword
#> 312
funny_add(1, c=3, b=2)    # One positional, 2 keyword
#> 321
funny_add(1, b=2)         # One positional, 1 keyword, 1 default
#> 121

121

### 2.2 Docstrings

In [10]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

In [11]:
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [13]:
def my_function(angle, trig_function):
        return trig_function(angle)

# Let's use the function
my_function(np.pi/2, np.sin)        
#> 1.0
my_function(np.pi/2, np.cos)        
#> 6.123233995736766e-17
my_function(np.pi/2, lambda x: np.cos(2*x))  
#> -1.0

-1.0

In [15]:
np.sin(np.pi/2)

1.0

### 2.4 More unpacking

In [16]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [17]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [18]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 [2, 3, 4] 5


In [19]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


## Exercise 1 :  A better calculator I

In [22]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([0, 66, 56, 24, 73])
z=np.array([0,0,0])
a = 4
b = 2

In [22]:
np.all(y!=0)

False

In [33]:
(y!=0).all()

False

In [51]:
def divide(x,y):
    x = np.array(x)
    y = np.array(y)
    assert (y!=0).all(), 'Divisor cannot be zero'       #condition: all elements are not equal to zero
    return x/y

In [52]:
divide(x,z)

AssertionError: Divisor cannot be zero

In [30]:
divide(4,2)

2.0

In [31]:
divide(x,b)

array([18. , 17. , 22. , 38. , 13.5])

In [32]:
divide(b,x)

array([0.05555556, 0.05882353, 0.04545455, 0.02631579, 0.07407407])

## Exercise 2 :  A better calculator II

In [22]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([0, 66, 56, 24, 73])
a = 4
b = 0

In [56]:
np.any(y!=0) 

True

In [25]:
def divide(x,y):
    x = np.array(x)
    y = np.array(y)
    np.seterr(divide='raise') 
    try:
        return x/y
    except:
        print('Divisor cannot be zero')

In [26]:
divide(x,a)

array([ 9.  ,  8.5 , 11.  , 19.  ,  6.75])

In [159]:
print(x/b)

[18.  17.  22.  38.  13.5]
