<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
import numpy as np

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [45]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [8]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [3]:
print(py_real_names[0])

Natasha Romanoff


In [4]:
print(py_super_names[0])

Black Widow


In [5]:
print(py_super_names[2])    

Doctor Strange


In [6]:
print(py_super_names[-1])   # Reverse indexing

Doctor Strange


### 1.3 Accessing data from a dictionary

In [9]:
print(superhero_info["Natasha Romanoff"])

Black Widow


In [10]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [11]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [12]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

In [14]:
print(py_superhero_info[0])

['Natasha Romanoff', 'Black Widow']


In [46]:
print(np_super_names[0])

Black Widow


## 2 Lists vs. Arrays

### 2.1 Size

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
len(py_list_2d)

10

In [16]:
len(np_array_2d)

10

In [17]:
np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [18]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
        
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [22]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [28]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)    
np_array * 2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [30]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [32]:
py_list == 3     # Works, but what IS the question?

False

In [34]:
np_array == 3  

array([False, False,  True, False, False])

In [35]:
np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [36]:
sum(py_list)     # sum() is a base Python function

15

In [37]:
max(py_list)     # max() is a base Python function

5

In [38]:
min(py_list)     # min() is a base Python function

1

In [39]:
np_array.sum()

15

In [40]:
np_array.mean()

3.0

In [41]:
np_array.max()

5

In [42]:
np_array.min()

1

## Exercise 1 :  Total recall?

**Two similarities between lists and arrays.**

1. We can retrieve an element from a list or array by an index which matches the elements position.

*2. We can determine the number of elements in lists and arrays with the len() function*

**Two differences between lists and arrays.**

*1. We can perform addition, subtraction, multiplication and division to an array, but not a list*

*2. We can obtain the mean of the elements in an array, but not a list*

**What is a dictionary?**

1. A dictionary is a medium to store data, and it stores data by matching keys to their respective values.

## Exercise 2 :  Index me

In [2]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                   
print(py_list[0:9:2])

['a1', 'c3', 'e5', 'g7', 'i9']


## Exercise 3 :  Capitalise Heroes

In [7]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [27]:
import array as arr # importing the array module

numbers= arr.array('i',[45, 60, 1, 30, 96, 1, 96, 57, 16, 1, 99, 
                        62, 86, 43, 42, 60, 59, 1, 1, 35, 83, 47,
                        34, 28, 68, 23, 22, 92, 1, 79, 1, 29, 94, 
                        72, 46, 47, 1, 74, 32, 20, 8, 37, 35, 1, 
                        89, 29, 86, 19, 43, 61])                        # creating an integer data type array

numbers.count(1) # printing the number of counts 

9

In [30]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

np_numbers = np.array(numbers)

sum(np_numbers == 1)

9