<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [ ]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one way to store data
x = py_list  # OR
x = np_array

### 1.2 Subsetting by masking (Arrays only)

In [1]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [2]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [3]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [4]:
np_array[~(np_array > 3)]                         # '~' means 'NOT'

array([1, 2, 3])

In [5]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [6]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [7]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[3]        # What is at position 4 (index 3)?

[4, 'D']

In [8]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

4

In [9]:
py_list_2d[:3]       # Elements from position 0 to 2

[[1, 'A'], [2, 'B'], [3, 'C']]

In [10]:
py_list_2d[:3][0]    # First element of the list

[1, 'A']

### 1.4 Indexing & Slicing 2D Arrays

In [14]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [12]:
np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U11')

In [15]:
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)

'4'

In [16]:
np_array_2d[:3]      # Elements from position 0 to 2

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [17]:
np_array_2d[:3, 0]   # FIRST element at positions 0 to 2 

array(['1', '2', '3'], dtype='<U11')

In [18]:
np_array_2d[3:6, 0]  # FIRST element at positions 3 to 5 

array(['4', '5', '6'], dtype='<U11')

In [19]:
np_array_2d[:, 0]    # FIRST element at all positions 

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [20]:
x=[1]*10
x               # I am lazy to type print()
                # Let Jupyter do the hard work.

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [21]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [22]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [23]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [24]:
x = [5]
y = [6]
x + y      # Just testing out how addition of lists work

[5, 6]

In [25]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [ ]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

## 2 Some loose ends

### 2.1 Tuples

In [ ]:
a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data

# Tuples cannot be modified after defining them

### 2.2 Be VERY careful when copying

In [26]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

|Term  |  Brief description  |
| :--- | :--: |
| Subsetting | *Picking out elements from a list*  | 
| Indexing   |  Picking out singular elements from a list/array based on their numerical position (starting from 0)  |
| Slicing   |  Picking out a **range** of elements from a list/array based on their numerical position (starting from 0)  |
| Masking   | Having True or False represent the elements when doing a selection  |

## Exercise 2 :  Show me the ‘odd’ letters

In [46]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_2d[:, 0]

new_array = np.array(np_array_2d[:, 0]).astype('int') % 2          # Converting all elements in np_array_2d to integers 
                                                                   # % array to get remainder of the array
np_array_2d[new_array > 0, 1]                       

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

In [31]:
np.array([1.1, 2.2, 3.3]).astype('int')     # Copied pasted from Google to see how astype(int) works

array([1, 2, 3])